# Generated by Django 2.1 on 2018-08-06 15:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Moneda')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='api.Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container', to='api.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_done', models.DateTimeField(default=None)),
                ('state', models.CharField(choices=[('STARTED', 'Started'), ('CANCELLED', 'Cancelled'), ('FINALIZED', 'Finalized')], default='STARTED', max_length=8, verbose_name='State')),
                ('ammount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('currency', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Currency')),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_account', to='api.Account')),
                ('origin_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_account', to='api.Account')),
            ],
            options={
                'verbose_name': 'Operacion',
                'verbose_name_plural': 'Operaciones',
                'ordering': ['-created'],
            },
        ),
    ]
